import { SeedData } from "../types";

export const seedData: SeedData = {
  Everley: {
    tier1: {
      words: [
        "the",
        "of",
        "and",
        "a",
        "to",
        "in",
        "is",
        "you",
        "that",
        "it",
        "he",
        "was",
        "for",
        "on",
        "are",
        "I",
        "we",
        "see",
        "look",
        "at",
        "like",
        "can",
        "my",
        "she",
        "go",
        "up",
        "me",
        "am",
        "no",
        "so",
      ],
      sentences: [
        "I see the cat.",
        "We look at the sun.",
        "It is a red bus.",
        "He can go to the map.",
        "She was on the log.",
        "You are in the van.",
        "I like my hat.",
        "That dog is in a pen.",
        "It is a cup of milk.",
        "We can go to the park.",
        "The hen and the pig are in a pen.",
        "It is for me.",
        "Look at my dad.",
        "You and I can see it.",
        "He was at the top.",
        "We are on a bus.",
        "She can go in it.",
        "We look for a bug.",
      ],
    },
    tier2: {
      words: [
        "so",
        "do",
        "an",
        "am",
        "no",
        "up",
        "me",
        "come",
        "yes",
        "play",
        "as",
        "with",
        "his",
        "they",
        "be",
        "this",
        "have",
        "from",
      ],
      sentences: [
        "I am at the bus.",
        "Can you come with me?",
        "Yes we can play.",
        "They go up the hill.",
        "Do we have a map?",
        "This is an ant.",
        "His hat is on the bed.",
        "I have no pen.",
        "Be on the mat.",
        "We play as we go.",
        "I got a pen from dad.",
        "It is so fun.",
        "He and she come up.",
        "They are with his cat.",
        "This can be for me.",
        "Yes they have it.",
        "I am up at the top.",
        "No I do this.",
      ],
    },
  },
  Presley: {
    tier1: {
      words: [
        "that",
        "then",
        "if",
        "but",
        "as",
        "of",
        "them",
        "with",
        "will",
        "all",
        "her",
        "us",
        "did",
        "get",
        "was",
        "his",
        "from",
        "be",
      ],
      sentences: [
        "That dog can run.",
        "If it is hot, sit.",
        "We run then rest.",
        "I like cats but not bees.",
        "He is as tall as dad.",
        "All of us can help.",
        "I will play with you.",
        "Give it to her.",
        "We see them here.",
        "He sat with his dog.",
        "We will get the ball.",
        "She was on her bed.",
        "His hat is red.",
        "I got it from Sam.",
        "Be on the mat.",
        "That was his hat.",
        "She did all that.",
        "Come with us to play.",
      ],
    },
    tier2: {
      words: [
        "they",
        "back",
        "each",
        "first",
        "want",
        "this",
        "have",
        "jump",
        "little",
        "went",
        "by",
        "what",
        "were",
        "when",
        "your",
        "going",
        "called",
        "has",
        "boy",
        "girl",
        "him",
        "said",
        "there",
        "put",
        "or",
        "more",
        "other",
        "here",
        "now",
        "down",
        "out",
        "about",
        "make",
        "made",
        "came",
        "time",
        "write",
        "read",
        "saw",
        "one",
        "use",
        "some",
        "these",
        "would",
        "could",
        "away",
        "may",
        "day",
        "way",
        "eat",
        "because",
        "been",
        "than",
        "too",
        "two",
        "who",
        "find",
        "very",
        "many",
        "off",
      ],
      sentences: [
        "They went back.",
        "Each kid went first.",
        "They were here first.",
        "I want this and have that.",
        "The little frogs jump.",
        "Sit by me when your mom is here.",
        "He is going to a game called Tag.",
        "The boy said the girl will help him.",
        "Put it there or get more.",
        "The other kids are here now.",
        "Go down and out to read about ants.",
        "We made it on time.",
        "She came at one.",
        "We read and write each day.",
        "Use these to make some art for one pal.",
        "We would go if we could.",
        "May we go away?",
        "We eat each day this way because mom said so.",
        "It has been more than two days, too.",
        "Who can find the very big box?",
        "Many are off.",
        "What did you see?",
        "I saw them at the park.",
      ],
    },
  },
};
